import { useEffect } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";

import { FeedbackRabbit } from "@/components/feedback-rabbit";
import { ScreenContainer } from "@/components/screen-container";
import { useFeedbackSounds } from "@/hooks/use-feedback-sounds";
import { ACTION_LAYOUT } from "@/lib/action-layout";

export default function CompleteScreen() {
  const router = useRouter(); const { title, stars, total, correct } = useLocalSearchParams<{ title: string; stars: string; total: string; correct: string }>(); const isPerfect = Number(correct) === Number(total); const { play, soundsEnabled, toggleSounds } = useFeedbackSounds();
  useEffect(() => { play("complete"); }, [play]);
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}><View style={styles.top}><Pressable accessibilityRole="switch" accessibilityState={{ checked: soundsEnabled }} accessibilityLabel={soundsEnabled ? "关闭通关音效" : "开启通关音效"} onPress={toggleSounds} style={styles.sound}><Text>{soundsEnabled ? "🔊" : "🔇"}</Text></Pressable></View><View style={styles.sparkles}><Text style={styles.sparkle}>✦</Text><Text style={styles.sparkleBig}>★</Text><Text style={styles.sparkle}>✦</Text></View><FeedbackRabbit state="complete" size={132} /><Text style={styles.title}>闯关完成！</Text><Text style={styles.subtitle}>{title}</Text><View style={styles.scoreCard}><View><Text style={styles.scoreValue}>{correct}/{total}</Text><Text style={styles.scoreLabel}>答对题数</Text></View><View style={styles.divider} /><View><Text style={styles.scoreValue}>+{stars}</Text><Text style={styles.scoreLabel}>获得星星</Text></View></View><Text style={styles.message}>{isPerfect ? "太棒了！兔兔已经把你的满分记录在成长册里。" : "你已经很勇敢了。把不熟的词放进复习卡，下次会更好！"}</Text><Pressable accessibilityRole="button" accessibilityLabel="回到闯关地图" onPress={() => router.replace("/(tabs)/map")} style={({ pressed }) => [styles.primary, pressed && { transform: [{ scale: 0.98 }] }]}><Text style={styles.primaryText}>回到闯关地图</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="去复习词汇" onPress={() => router.replace("/(tabs)/review")} style={({ pressed }) => [styles.secondary, pressed && { opacity: 0.72 }]}><Text style={styles.secondaryText}>去复习词汇</Text></Pressable></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ page: { flexGrow: 1, alignItems: "center", justifyContent: "center", padding: 28, paddingBottom: 42, backgroundColor: "#FFF9F0" }, top: { position: "absolute", top: 20, right: 20 }, sound: { width: 36, height: 36, borderRadius: 18, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EEE7DE", alignItems: "center", justifyContent: "center" }, sparkles: { width: "100%", flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 35, marginBottom: -1 }, sparkle: { color: "#EBAA31", fontSize: 19 }, sparkleBig: { color: "#EBAA31", fontSize: 27, marginTop: -7 }, title: { color: "#2E2A25", fontSize: 30, fontWeight: "900", marginTop: 18 }, subtitle: { color: "#736B62", fontSize: 15, marginTop: 7 }, scoreCard: { width: "100%", borderRadius: 24, backgroundColor: "#FFFFFF", padding: 21, marginTop: 28, flexDirection: "row", alignItems: "center", justifyContent: "space-evenly", borderWidth: 1, borderColor: "#F0E7DA" }, scoreValue: { textAlign: "center", color: "#F06D28", fontSize: 25, fontWeight: "900" }, scoreLabel: { textAlign: "center", color: "#80776D", fontSize: 12, fontWeight: "700", marginTop: 5 }, divider: { width: 1, height: 42, backgroundColor: "#EEE7DE" }, message: { color: "#6D655D", lineHeight: 22, textAlign: "center", marginTop: 22, fontSize: 14 }, primary: { width: "100%", minHeight: ACTION_LAYOUT.primaryMinHeight, justifyContent: "center", backgroundColor: "#F5803E", borderRadius: ACTION_LAYOUT.primaryRadius, alignItems: "center", paddingVertical: 12, marginTop: 26 }, primaryText: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" }, secondary: { width: "100%", minHeight: ACTION_LAYOUT.secondaryMinHeight, justifyContent: "center", borderRadius: ACTION_LAYOUT.primaryRadius, alignItems: "center", paddingVertical: 11, marginTop: 7 }, secondaryText: { color: "#A45D23", fontSize: 14, fontWeight: "900" } });
