import { useMemo, useState } from "react";
import { Platform, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import * as Haptics from "expo-haptics";

import { FeedbackRabbit, type RabbitFeedbackState } from "@/components/feedback-rabbit";
import { ScreenContainer } from "@/components/screen-container";
import { TransitionIn } from "@/components/transition-in";
import { getBunnyMicroStory, getStoryCloze, getStorySentences } from "@/lib/material-learning";
import { recordMicroStoryCompletion, recordModuleActivity, recordStoryClozeMistake } from "@/lib/learning-progress";
import { speakEnglish } from "@/lib/speech";

const stepTitles = ["听读故事", "重点词填空", "勇敢跟读"];

export default function MicroStoryChallengeScreen() {
  const router = useRouter();
  const { level } = useLocalSearchParams<{ level: string }>();
  const story = getBunnyMicroStory(level ?? "");
  const cloze = useMemo(() => story ? getStoryCloze(story) : null, [story]);
  const sentences = useMemo(() => story ? getStorySentences(story) : [], [story]);
  const [step, setStep] = useState(0);
  const [sentenceIndex, setSentenceIndex] = useState(0);
  const [selected, setSelected] = useState<string | null>(null);
  const [rabbitState, setRabbitState] = useState<RabbitFeedbackState>("idle");
  const [completed, setCompleted] = useState<{ isNew: boolean; reward: number } | null>(null);
  const [isFinishing, setIsFinishing] = useState(false);

  if (!story || !cloze) return <ScreenContainer className="items-center justify-center p-6"><Text style={styles.error}>这篇兔兔微故事暂时还没有准备好。</Text><Pressable onPress={() => router.back()} style={styles.primary}><Text style={styles.primaryText}>返回练习</Text></Pressable></ScreenContainer>;

  const notify = (good: boolean) => { if (Platform.OS !== "web") Haptics.notificationAsync(good ? Haptics.NotificationFeedbackType.Success : Haptics.NotificationFeedbackType.Error); };
  const choose = async (word: string) => {
    if (selected) return;
    const right = word === cloze.answer;
    setSelected(word);
    setRabbitState(right ? "success" : "retry");
    notify(right);
    await recordModuleActivity("micro-story", { correct: right });
    if (!right) void recordStoryClozeMistake(cloze.answer);
  };
  const nextAfterCloze = () => { if (selected === cloze.answer) { setStep(2); setSentenceIndex(0); setSelected(null); setRabbitState("idle"); } else { setSelected(null); setRabbitState("idle"); } };
  const finish = async () => { if (isFinishing) return; setIsFinishing(true); try { const result = await recordMicroStoryCompletion(story.levelId); setCompleted({ isNew: result.isNew, reward: result.reward }); setRabbitState("success"); notify(true); } finally { setIsFinishing(false); } };
  const nextSentence = (nextStep?: number) => { if (sentenceIndex < sentences.length - 1) { setSentenceIndex((index) => index + 1); return; } if (nextStep !== undefined) { setStep(nextStep); setSentenceIndex(0); } };

  const content = step === 0 ? <View style={styles.content}><Text style={styles.helper}>一句一句慢慢听，眼睛跟着故事走</Text><Text style={styles.sentenceCount}>第 {sentenceIndex + 1}/{sentences.length} 句</Text><Text style={styles.story}>{sentences[sentenceIndex]}</Text><Pressable accessibilityRole="button" accessibilityLabel="慢速播放当前故事句子" onPress={() => speakEnglish(sentences[sentenceIndex], true)} style={styles.listen}><Text style={styles.listenText}>🔊 慢速听这一句</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="进入下一句或填空" onPress={() => nextSentence(1)} style={styles.primary}><Text style={styles.primaryText}>{sentenceIndex < sentences.length - 1 ? "下一句" : "我已听读，开始填空"}</Text></Pressable></View> : step === 1 ? <View style={styles.content}><Text style={styles.helper}>选出最合适的重点词，把故事补完整</Text><Text style={styles.cloze}>{cloze.prompt}</Text><View style={styles.options}>{cloze.options.map((word) => { const right = word === cloze.answer; const chosen = word === selected; return <Pressable key={word} accessibilityRole="button" accessibilityLabel={`选择${word}`} disabled={Boolean(selected)} onPress={() => choose(word)} style={[styles.option, selected && right && styles.correct, selected && chosen && !right && styles.wrong]}><Text style={[styles.optionText, selected && right && styles.correctText]}>{word}</Text></Pressable>; })}</View>{selected ? <View style={[styles.feedback, selected === cloze.answer ? styles.goodFeedback : styles.retryFeedback]}><Text style={styles.feedbackTitle}>{selected === cloze.answer ? "补对啦！" : `“${cloze.answer}”已加入复习列表`}</Text><Pressable accessibilityRole="button" accessibilityLabel="继续故事挑战" onPress={nextAfterCloze} style={styles.feedbackButton}><Text style={styles.feedbackButtonText}>{selected === cloze.answer ? "进入跟读" : "再试一次"}</Text></Pressable></View> : null}</View> : <View style={styles.content}><Text style={styles.helper}>一句一句慢速跟读，读完再继续</Text><Text style={styles.sentenceCount}>第 {sentenceIndex + 1}/{sentences.length} 句</Text><Text style={styles.story}>{sentences[sentenceIndex]}</Text><Pressable accessibilityRole="button" accessibilityLabel="慢速播放当前跟读句子" onPress={() => speakEnglish(sentences[sentenceIndex], true)} style={styles.listen}><Text style={styles.listenText}>🔊 慢速示范这一句</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="完成本句跟读" onPress={() => sentenceIndex < sentences.length - 1 ? nextSentence() : finish()} style={styles.primary}><Text style={styles.primaryText}>{sentenceIndex < sentences.length - 1 ? "🎙 我已跟读这一句" : "🎙 完成故事跟读"}</Text></Pressable></View>;

  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.scroll}><View style={styles.top}><Pressable accessibilityRole="button" accessibilityLabel="返回材料练习" onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><View><Text style={styles.kicker}>兔兔微故事挑战 · {story.levelId}</Text><Text style={styles.title}>{story.title}</Text></View><FeedbackRabbit state={rabbitState} size={52} /></View><View style={styles.progressRow}>{stepTitles.map((title, index) => <View key={title} style={styles.stepItem}><View style={[styles.stepDot, index <= step && styles.stepDotActive]}><Text style={[styles.stepNo, index <= step && styles.stepNoActive]}>{index + 1}</Text></View><Text style={[styles.stepLabel, index === step && styles.stepLabelActive]}>{title}</Text></View>)}</View><View style={styles.card}><Text style={styles.theme}>{story.theme}</Text><Text style={styles.focus}>重点词：{story.focusWords.join(" · ")}</Text><TransitionIn trigger={`${step}-${sentenceIndex}`}>{content}</TransitionIn></View>{completed ? <TransitionIn trigger="story-complete"><View style={styles.completeCard}><Text style={styles.completeIcon}>🏅</Text><Text style={styles.completeTitle}>{completed.isNew ? "故事徽章已点亮！" : "这篇故事已完成过啦！"}</Text><Text style={styles.completeBody}>{completed.isNew ? `获得 ${completed.reward} 颗星星，继续保持勇敢开口。` : "再读一次，也是在给英语耳朵充电。"}</Text><Pressable accessibilityRole="button" accessibilityLabel="返回材料练习" onPress={() => router.back()} style={styles.primary}><Text style={styles.primaryText}>返回材料练习</Text></Pressable></View></TransitionIn> : null}{isFinishing ? <Text style={styles.finishing}>兔兔正在点亮故事徽章…</Text> : null}</ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({
  scroll: { flexGrow: 1, backgroundColor: "#FFF9F0", padding: 20, paddingBottom: 30 }, top: { flexDirection: "row", alignItems: "center", gap: 10 }, back: { width: 38, height: 38, borderRadius: 19, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#EEE7DE" }, backText: { color: "#6E665E", fontSize: 30, marginTop: -4 }, kicker: { color: "#A66A2E", fontSize: 11, fontWeight: "900" }, title: { color: "#493B2B", fontSize: 20, fontWeight: "900", marginTop: 2, maxWidth: 210 }, error: { color: "#5F574F", fontSize: 15, textAlign: "center" },
  progressRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 22 }, stepItem: { flex: 1, alignItems: "center" }, stepDot: { width: 29, height: 29, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: "#E8DFD3" }, stepDotActive: { backgroundColor: "#F5803E" }, stepNo: { color: "#8B8177", fontSize: 13, fontWeight: "900" }, stepNoActive: { color: "#FFFFFF" }, stepLabel: { color: "#958A7E", fontSize: 10, marginTop: 5, fontWeight: "800" }, stepLabelActive: { color: "#A65B1B" },
  card: { backgroundColor: "#FFFFFF", borderRadius: 24, padding: 19, marginTop: 18, borderWidth: 1, borderColor: "#F0E2D1" }, theme: { color: "#A66A2E", fontSize: 12, fontWeight: "900" }, focus: { color: "#857262", fontSize: 11, marginTop: 5, lineHeight: 17, fontWeight: "700" }, content: { marginTop: 18 }, helper: { color: "#887E75", fontSize: 12, fontWeight: "800" }, sentenceCount: { color: "#A66A2E", backgroundColor: "#FFF0D7", alignSelf: "flex-start", borderRadius: 10, paddingHorizontal: 9, paddingVertical: 5, overflow: "hidden", fontSize: 11, fontWeight: "900", marginTop: 12 }, story: { color: "#41382F", fontSize: 17, lineHeight: 27, fontWeight: "800", marginTop: 10 }, cloze: { color: "#41382F", fontSize: 16, lineHeight: 26, fontWeight: "800", marginTop: 10 }, listen: { alignSelf: "flex-start", backgroundColor: "#EEEAFE", borderRadius: 13, paddingHorizontal: 14, paddingVertical: 11, marginTop: 18 }, listenText: { color: "#5B55A2", fontSize: 13, fontWeight: "900" }, primary: { backgroundColor: "#F5803E", borderRadius: 16, paddingVertical: 13, paddingHorizontal: 18, alignItems: "center", marginTop: 18 }, primaryText: { color: "#FFFFFF", fontSize: 14, fontWeight: "900" }, options: { gap: 10, marginTop: 18 }, option: { minHeight: 52, borderRadius: 15, borderWidth: 2, borderColor: "#E9E2D9", justifyContent: "center", paddingHorizontal: 15, backgroundColor: "#FFFDF9" }, optionText: { color: "#44392F", fontSize: 15, fontWeight: "900" }, correct: { borderColor: "#46A758", backgroundColor: "#E3F7E8" }, wrong: { borderColor: "#D6595F", backgroundColor: "#FDE9E9" }, correctText: { color: "#277B3B" }, feedback: { borderRadius: 16, padding: 13, marginTop: 15 }, goodFeedback: { backgroundColor: "#E3F7E8" }, retryFeedback: { backgroundColor: "#FFF0D7" }, feedbackTitle: { color: "#6A5039", fontSize: 14, fontWeight: "900" }, feedbackButton: { marginTop: 9, backgroundColor: "#F5803E", borderRadius: 12, paddingVertical: 10, alignItems: "center" }, feedbackButtonText: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" }, completeCard: { backgroundColor: "#FFF0D3", borderRadius: 22, padding: 20, marginTop: 16, alignItems: "center", borderWidth: 1, borderColor: "#F7C85E" }, completeIcon: { fontSize: 44 }, completeTitle: { color: "#754B23", fontSize: 18, fontWeight: "900", marginTop: 4 }, completeBody: { color: "#8D6743", fontSize: 13, lineHeight: 20, textAlign: "center", marginTop: 6 }, finishing: { color: "#8A5B2A", fontSize: 13, fontWeight: "900", textAlign: "center", marginTop: 14 },
});
