import { useCallback, useMemo, useState } from "react";
import { Alert, Platform, Pressable, StyleSheet, Text, View } from "react-native";
import { useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import { File, Paths } from "expo-file-system";
import * as Sharing from "expo-sharing";
import Svg, { Circle, Rect, Text as SvgText } from "react-native-svg";

import { createAchievementPosterSvg } from "@/lib/achievement-poster";
import { getRareBadges } from "@/lib/badge-collection";
import { DEFAULT_PROGRESS, getActiveProfile, LearningProgress } from "@/lib/learning-progress";
import { ScreenContainer } from "@/components/screen-container";

export default function AchievementPosterScreen() {
  const router = useRouter();
  const { badgeId } = useLocalSearchParams<{ badgeId: string }>();
  const [name, setName] = useState("小兔同学");
  const [progress, setProgress] = useState<LearningProgress>(DEFAULT_PROGRESS);
  useFocusEffect(useCallback(() => { getActiveProfile().then((profile) => { setName(profile.name); setProgress(profile.progress); }); }, []));
  const badge = getRareBadges(progress).find((item) => item.id === badgeId);
  const acquiredAt = badge ? progress.rareBadgeUnlockedAt[badge.id] ?? "历史解锁" : "";
  const svg = useMemo(() => badge ? createAchievementPosterSvg({ studentName: name, badgeName: badge.name, badgeIcon: badge.icon, acquiredAt }) : "", [acquiredAt, badge, name]);
  const share = async () => { if (!badge || !badge.unlocked) return; if (Platform.OS === "web") { const blob = new Blob([svg], { type: "image/svg+xml" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `兔兔英语_${name}_${badge.name}_纪念卡.svg`; anchor.click(); URL.revokeObjectURL(url); return; } const file = new File(Paths.cache, `兔兔英语_${name}_${badge.name}_纪念卡.svg`); file.create({ overwrite: true, intermediates: true }); file.write(svg); if (!(await Sharing.isAvailableAsync())) { Alert.alert("当前设备不支持分享", "纪念海报已生成，但无法打开系统分享面板。"); return; } await Sharing.shareAsync(file.uri, { mimeType: "image/svg+xml", dialogTitle: "分享我的英语成就" }); };
  if (!badge || !badge.unlocked) return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.empty}><Text style={styles.emptyTitle}>这枚徽章还在等待解锁</Text><Pressable accessibilityRole="button" accessibilityLabel="返回徽章墙" onPress={() => router.back()} style={styles.backButton}><Text style={styles.backText}>回到徽章墙</Text></Pressable></View></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.page}><View style={styles.top}><Pressable accessibilityRole="button" accessibilityLabel="返回徽章墙" onPress={() => router.back()} style={styles.back}><Text style={styles.backChevron}>‹</Text></Pressable><Text style={styles.title}>成就纪念海报</Text><View style={styles.placeholder} /></View><View style={styles.poster}><Svg width="100%" height="100%" viewBox="0 0 360 480"><Rect width="360" height="480" fill="#F7F0DE"/><Circle cx="316" cy="49" r="58" fill="#F7C55C" opacity={0.35}/><Circle cx="45" cy="426" r="70" fill="#7B6FEA" opacity={0.16}/><SvgText x="180" y="70" textAnchor="middle" fontSize="15" fontWeight="700" fill="#6E5BA9">兔兔英语闯关</SvgText><SvgText x="180" y="102" textAnchor="middle" fontSize="23" fontWeight="800" fill="#413766">成就纪念卡</SvgText><Rect x="38" y="130" width="284" height="260" rx="22" fill="#FFFFFF"/><SvgText x="180" y="200" textAnchor="middle" fontSize="61">{badge.icon}</SvgText><SvgText x="180" y="246" textAnchor="middle" fontSize="16" fontWeight="700" fill="#9A7B3B">恭喜 {name}</SvgText><SvgText x="180" y="286" textAnchor="middle" fontSize="24" fontWeight="800" fill="#3C315F">{badge.name}</SvgText><SvgText x="180" y="320" textAnchor="middle" fontSize="12" fill="#756A86">已成功解锁稀有隐藏徽章</SvgText><SvgText x="180" y="358" textAnchor="middle" fontSize="11" fill="#7C7066">获得日期：{acquiredAt}</SvgText><SvgText x="180" y="436" textAnchor="middle" fontSize="15" fontWeight="700" fill="#6B5DA5">一步一星，勇敢成长</SvgText></Svg></View><Text style={styles.caption}>海报仅包含当前学生昵称、徽章名称与获得日期，不含学习录音或题目记录。</Text><Pressable accessibilityRole="button" accessibilityLabel="生成并分享成就纪念海报" onPress={share} style={styles.shareButton}><Text style={styles.shareText}>{Platform.OS === "web" ? "下载纪念海报" : "生成并分享海报"}</Text></Pressable></View></ScreenContainer>;
}

const styles = StyleSheet.create({ page: { flex: 1, padding: 20, backgroundColor: "#FFF9F0" }, top: { flexDirection: "row", alignItems: "center", marginBottom: 20 }, back: { width: 38, height: 38, borderRadius: 19, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EEE7DE", alignItems: "center", justifyContent: "center" }, backChevron: { color: "#6E665E", fontSize: 31, marginTop: -4 }, title: { flex: 1, textAlign: "center", color: "#2E2A25", fontSize: 16, fontWeight: "900" }, placeholder: { width: 38 }, poster: { alignSelf: "center", width: "92%", aspectRatio: 0.75, borderRadius: 22, overflow: "hidden", shadowColor: "#6A5A44", shadowOpacity: 0.12, shadowRadius: 10, shadowOffset: { width: 0, height: 6 }, elevation: 4 }, caption: { color: "#877D73", fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 17, paddingHorizontal: 16 }, shareButton: { alignItems: "center", backgroundColor: "#7B6FEA", borderRadius: 15, paddingVertical: 14, marginTop: 18 }, shareText: { color: "#FFFFFF", fontSize: 15, fontWeight: "900" }, empty: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: "#FFF9F0", padding: 24 }, emptyTitle: { color: "#4B433C", fontSize: 18, fontWeight: "900" }, backButton: { backgroundColor: "#7B6FEA", borderRadius: 14, paddingHorizontal: 18, paddingVertical: 12, marginTop: 15 }, backText: { color: "#FFFFFF", fontSize: 14, fontWeight: "900" } });
