import { useCallback, useMemo, useState } from "react";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useFocusEffect, useRouter } from "expo-router";

import { BOSS_THEMES } from "@/lib/boss-themes";
import { getBadgeCollectionState, getBadgeMilestoneReward } from "@/lib/badge-collection";
import { claimBadgeCollectionMilestone, DEFAULT_PROGRESS, getActiveProfile, LearningProgress } from "@/lib/learning-progress";
import { LEVELS } from "@/lib/learning-data";
import { BUNNY_MICRO_STORIES, getMaterialBatchBadge, getMaterialBatchCount } from "@/lib/material-learning";
import { getUploadedWordsForLevel } from "@/lib/uploaded-vocabulary";
import { ParticleCelebration } from "@/components/particle-celebration";
import { ScreenContainer } from "@/components/screen-container";

const acquired = (date?: string) => date ? `获得于 ${date}` : "历史解锁（日期未存）";

export default function BadgeWallScreen() {
  const router = useRouter();
  const [progress, setProgress] = useState<LearningProgress>(DEFAULT_PROGRESS);
  const [celebrating, setCelebrating] = useState(false);
  useFocusEffect(useCallback(() => { let active = true; getActiveProfile().then((profile) => { if (active) setProgress(profile.progress); }); return () => { active = false; }; }, []));

  const state = getBadgeCollectionState(progress);
  const materialBadges = useMemo(() => BUNNY_MICRO_STORIES.flatMap((story) => Array.from({ length: getMaterialBatchCount(getUploadedWordsForLevel(story.levelId).length) }, (_, batchIndex) => ({ levelId: story.levelId, ...getMaterialBatchBadge(story.levelId, batchIndex) }))), []);
  const materialCollected = materialBadges.filter((badge) => Boolean(progress.materialBatchBadges[badge.id])).length;
  const materialProgress = materialBadges.length ? (materialCollected / materialBadges.length) * 100 : 0;
  const claim = async () => { if (!state.nextMilestone) return; const updated = await claimBadgeCollectionMilestone(state.nextMilestone, getBadgeMilestoneReward(state.nextMilestone)); setProgress(updated); setCelebrating(true); };

  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.page}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.top}><Pressable accessibilityRole="button" accessibilityLabel="返回学习地图" onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><Text style={styles.title}>BOSS 徽章图鉴</Text><Text style={styles.count}>{state.collectedTotal}/10</Text></View>
    <View style={styles.hero}><Text style={styles.heroTitle}>每一枚星徽，都是一次成长</Text><Text style={styles.heroBody}>等级徽章来自BOSS挑战；短练习徽章来自持续收集新词。</Text><View style={styles.progressRow}><View style={styles.track}><View style={[styles.trackFill, { width: `${(state.coreCompleted / state.coreTotal) * 100}%` }]} /></View><Text style={styles.progressText}>等级 {state.coreCompleted}/7</Text></View></View>
    {state.nextMilestone ? <Pressable accessibilityRole="button" accessibilityLabel={`领取收集${state.nextMilestone}枚徽章的阶段奖励`} onPress={claim} style={styles.rewardCard}><Text style={styles.rewardIcon}>🎁</Text><View style={styles.rewardCopy}><Text style={styles.rewardTitle}>阶段奖励已到！</Text><Text style={styles.rewardBody}>收集 {state.nextMilestone} 枚等级星徽，可领取 {getBadgeMilestoneReward(state.nextMilestone)} 颗奖励星星。</Text></View><Text style={styles.rewardAction}>领取</Text></Pressable> : <View style={styles.lockedReward}><Text style={styles.lockedText}>{state.coreCompleted >= 7 ? "等级星徽奖励已全部领取" : `再收集 ${Math.max(0, 3 - state.coreCompleted)} 枚等级星徽，可获得下一份奖励`}</Text></View>}
    <Text style={styles.sectionTitle}>等级星徽</Text><View style={styles.grid}>{BOSS_THEMES.map((theme) => { const level = LEVELS.find((item) => item.id === theme.levelId); const unlocked = progress.bossCompletedLevelIds.includes(theme.levelId); return <View key={theme.levelId} style={[styles.card, !unlocked && styles.cardLocked]}>{theme.imageUri ? <Image source={{ uri: theme.imageUri }} style={styles.scene} resizeMode="cover" /> : <View style={[styles.scene, styles.fallbackScene]}><Text style={styles.fallbackEmoji}>🌙</Text></View>}<View style={[styles.medal, { backgroundColor: unlocked ? theme.accent : "#B9B4AD" }]}><Text style={styles.medalText}>{unlocked ? theme.badgeIcon : "🔒"}</Text></View><Text style={styles.level}>{level?.title}</Text><Text style={styles.name}>{unlocked ? theme.badgeName : "等待挑战"}</Text><Text style={styles.sceneLabel}>{theme.scene}</Text><Text style={styles.acquired}>{unlocked ? acquired(progress.bossCompletedAt[theme.levelId]) : "条件：完成本等级8个主题关后挑战BOSS"}</Text></View>; })}</View>
    <Text style={styles.sectionTitle}>稀有发现</Text><View style={styles.rareList}>{state.rareBadges.map((badge) => <View key={badge.id} style={[styles.rareCard, !badge.unlocked && styles.rareLocked]}><Text style={styles.rareIcon}>{badge.unlocked ? badge.icon : "❔"}</Text><View style={styles.rareCopy}><Text style={styles.rareName}>{badge.unlocked ? badge.name : "神秘稀有徽章"}</Text><Text style={styles.rareHint}>条件：{badge.hint}</Text><View style={styles.rareTrack}><View style={[styles.rareFill, { width: `${Math.min(100, (badge.progress / badge.goal) * 100)}%` }]} /></View><Text style={styles.rareProgress}>{badge.progress}/{badge.goal}{badge.unlocked ? ` · ${acquired(progress.rareBadgeUnlockedAt[badge.id])}` : ""}</Text>{badge.unlocked ? <Pressable accessibilityRole="button" accessibilityLabel={`为${badge.name}生成纪念海报`} onPress={() => router.push({ pathname: "/achievement-poster", params: { badgeId: badge.id } } as never)} style={styles.posterButton}><Text style={styles.posterButtonText}>生成纪念海报</Text></Pressable> : null}</View></View>)}</View>
    <Text style={styles.sectionTitle}>短练习小徽章</Text><View style={styles.materialHero}><View style={styles.materialHeroRow}><View><Text style={styles.materialHeroTitle}>12词收集进度</Text><Text style={styles.materialHeroBody}>每完成一组新词练习，就能点亮一枚专属小徽章。</Text></View><Text style={styles.materialNumber}>{materialCollected}/{materialBadges.length}</Text></View><View style={styles.materialTrack}><View style={[styles.materialFill, { width: `${materialProgress}%` }]} /></View></View>
    <View style={styles.materialGrid}>{materialBadges.map((badge) => { const earned = progress.materialBatchBadges[badge.id]; return <View key={badge.id} style={[styles.materialBadge, !earned && styles.materialBadgeLocked]}><Text style={styles.materialIcon}>{earned ? badge.icon : "🔒"}</Text><Text style={styles.materialLevel}>{badge.levelId} · 第{badge.id.split("-").pop()}组</Text><Text style={styles.materialName}>{earned ? badge.title : "等待收集"}</Text><Text style={styles.materialDate}>{earned ? acquired(earned.earnedAt) : "完成本组12词练习"}</Text></View>; })}</View>
    <View style={styles.legend}><Text style={styles.legendTitle}>图鉴说明</Text><Text style={styles.legendText}>新获得的徽章会记录本机日期；以前的历史徽章若没有日期记录，会明确标为“历史解锁”。</Text></View>
  </ScrollView><ParticleCelebration visible={celebrating} onFinished={() => setCelebrating(false)} /></View></ScreenContainer>;
}

const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: "#FFF9F0" }, content: { padding: 20, paddingBottom: 34 }, top: { flexDirection: "row", alignItems: "center" }, back: { width: 38, height: 38, borderRadius: 19, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EEE7DE", alignItems: "center", justifyContent: "center" }, backText: { color: "#6E665E", fontSize: 31, marginTop: -4 }, title: { flex: 1, textAlign: "center", color: "#2E2A25", fontSize: 16, fontWeight: "900" }, count: { minWidth: 38, textAlign: "right", color: "#5D58B5", fontSize: 13, fontWeight: "900" },
  hero: { backgroundColor: "#F3EEFF", borderRadius: 23, padding: 18, marginTop: 19 }, heroTitle: { color: "#4D4385", fontSize: 19, fontWeight: "900" }, heroBody: { color: "#706887", fontSize: 13, lineHeight: 19, marginTop: 6 }, progressRow: { flexDirection: "row", alignItems: "center", gap: 9, marginTop: 14 }, track: { flex: 1, height: 10, backgroundColor: "#D9D4EF", borderRadius: 8, overflow: "hidden" }, trackFill: { height: "100%", backgroundColor: "#7B6FEA", borderRadius: 8 }, progressText: { color: "#5D58B5", fontSize: 11, fontWeight: "900" },
  rewardCard: { flexDirection: "row", alignItems: "center", backgroundColor: "#FFF0D7", padding: 14, borderRadius: 18, marginTop: 12 }, rewardIcon: { fontSize: 27, marginRight: 10 }, rewardCopy: { flex: 1 }, rewardTitle: { color: "#A65B1B", fontSize: 14, fontWeight: "900" }, rewardBody: { color: "#8A643E", fontSize: 11, lineHeight: 16, marginTop: 3 }, rewardAction: { color: "#FFFFFF", backgroundColor: "#F5803E", borderRadius: 12, overflow: "hidden", paddingHorizontal: 10, paddingVertical: 7, fontSize: 11, fontWeight: "900" }, lockedReward: { backgroundColor: "#F6F2EC", borderRadius: 15, padding: 11, marginTop: 12 }, lockedText: { color: "#817970", fontSize: 11, textAlign: "center", fontWeight: "800" },
  sectionTitle: { color: "#2E2A25", fontSize: 16, fontWeight: "900", marginTop: 22, marginBottom: 9 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 12 }, card: { width: "47.8%", backgroundColor: "#FFFFFF", borderRadius: 19, overflow: "hidden", paddingBottom: 12, alignItems: "center", borderWidth: 1, borderColor: "#EEE6DC" }, cardLocked: { opacity: 0.62 }, scene: { width: "100%", height: 83, backgroundColor: "#E6E0D7" }, fallbackScene: { alignItems: "center", justifyContent: "center", backgroundColor: "#30365F" }, fallbackEmoji: { fontSize: 35 }, medal: { width: 43, height: 43, borderRadius: 22, marginTop: -20, alignItems: "center", justifyContent: "center", borderWidth: 3, borderColor: "#FFF9F0" }, medalText: { fontSize: 21 }, level: { color: "#877E75", fontSize: 11, fontWeight: "800", marginTop: 8 }, name: { color: "#342F2A", fontSize: 13, fontWeight: "900", marginTop: 2 }, sceneLabel: { color: "#988F86", fontSize: 10, marginTop: 3 }, acquired: { color: "#847A71", fontSize: 9, lineHeight: 13, marginTop: 5, textAlign: "center", paddingHorizontal: 7 },
  rareList: { gap: 9 }, rareCard: { flexDirection: "row", backgroundColor: "#FFF8E9", borderRadius: 17, padding: 12, borderWidth: 1, borderColor: "#F2DDB2" }, rareLocked: { backgroundColor: "#F2EFEB", borderColor: "#E3DED8" }, rareIcon: { fontSize: 27, marginRight: 10, alignSelf: "center" }, rareCopy: { flex: 1 }, rareName: { color: "#594124", fontSize: 13, fontWeight: "900" }, rareHint: { color: "#7C6C5C", fontSize: 11, lineHeight: 16, marginTop: 2 }, rareTrack: { height: 6, backgroundColor: "#E5DED6", borderRadius: 5, overflow: "hidden", marginTop: 7 }, rareFill: { height: "100%", backgroundColor: "#F2B84B", borderRadius: 5 }, rareProgress: { color: "#967A4B", fontSize: 10, textAlign: "right", marginTop: 3, fontWeight: "800" }, posterButton: { alignSelf: "flex-start", backgroundColor: "#7B6FEA", borderRadius: 10, paddingHorizontal: 10, paddingVertical: 7, marginTop: 8 }, posterButtonText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" },
  materialHero: { backgroundColor: "#EAF5ED", borderRadius: 18, padding: 14 }, materialHeroRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, materialHeroTitle: { color: "#307342", fontSize: 14, fontWeight: "900" }, materialHeroBody: { color: "#5A8064", fontSize: 11, lineHeight: 16, marginTop: 3, maxWidth: 235 }, materialNumber: { color: "#278345", fontSize: 18, fontWeight: "900" }, materialTrack: { height: 8, backgroundColor: "#CFE7D5", borderRadius: 6, overflow: "hidden", marginTop: 12 }, materialFill: { height: "100%", backgroundColor: "#47A860", borderRadius: 6 }, materialGrid: { flexDirection: "row", flexWrap: "wrap", gap: 9 }, materialBadge: { width: "31.6%", minHeight: 115, backgroundColor: "#FFFDF7", borderRadius: 15, borderWidth: 1, borderColor: "#E7DBC9", padding: 9, alignItems: "center", justifyContent: "center" }, materialBadgeLocked: { backgroundColor: "#F1EFEA", borderColor: "#E1DDD5" }, materialIcon: { fontSize: 25 }, materialLevel: { color: "#81786F", fontSize: 9, marginTop: 4, fontWeight: "900" }, materialName: { color: "#5A493A", fontSize: 10, lineHeight: 14, textAlign: "center", fontWeight: "900", marginTop: 3 }, materialDate: { color: "#8E8172", fontSize: 8, lineHeight: 11, textAlign: "center", marginTop: 4 },
  legend: { backgroundColor: "#EAF5ED", borderRadius: 15, padding: 13, marginTop: 16 }, legendTitle: { color: "#307342", fontSize: 12, fontWeight: "900" }, legendText: { color: "#5A8064", fontSize: 11, lineHeight: 16, marginTop: 5 },
});
