import { useCallback, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect, useRouter } from "expo-router";

import { isParentSessionUnlocked, setParentPin, verifyParentPin } from "@/lib/parent-security";
import { ScreenContainer } from "@/components/screen-container";

export default function ChangePinScreen() {
  const router = useRouter(); const [current, setCurrent] = useState(""); const [next, setNext] = useState(""); const [confirm, setConfirm] = useState(""); const [busy, setBusy] = useState(false);
  useFocusEffect(useCallback(() => { isParentSessionUnlocked().then((unlocked) => { if (!unlocked) router.replace({ pathname: "/parent-gate", params: { target: "parent-settings" } } as never); }); }, [router]));
  const save = async () => { if (next !== confirm) { Alert.alert("两次PIN不一致", "请重新确认新的4位PIN码。" ); return; } setBusy(true); try { const verified = await verifyParentPin(current); if (!verified.success) throw new Error(verified.reason === "locked" ? "PIN暂时锁定，请稍后重试。" : "当前PIN码不正确。"); await setParentPin(next); Alert.alert("PIN已修改", "新的PIN现在已生效；如需生物识别，请在家长设置中重新开启。", [{ text: "好", onPress: () => router.back() }]); } catch (error) { Alert.alert("未能修改PIN", error instanceof Error ? error.message : "请稍后重试。" ); } finally { setBusy(false); } };
  const input = (value: string, setter: (text: string) => void, label: string) => <><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={(text) => setter(text.replace(/\D/g, "").slice(0, 4))} keyboardType="number-pad" secureTextEntry maxLength={4} placeholder="••••" placeholderTextColor="#B5ADA4" style={styles.input} /></>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.page}><Pressable accessibilityRole="button" accessibilityLabel="返回家长设置" onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><Text style={styles.title}>修改家长PIN</Text><Text style={styles.subtitle}>请先验证当前PIN，再设置新的4位数字PIN。修改后，生物识别选项需要重新开启。</Text><View style={styles.card}>{input(current, setCurrent, "当前PIN")}{input(next, setNext, "新的PIN")}{input(confirm, setConfirm, "确认新的PIN")}<Pressable accessibilityRole="button" accessibilityLabel="保存新的家长PIN" onPress={save} disabled={busy} style={[styles.save, busy && { opacity: 0.6 }]}><Text style={styles.saveText}>{busy ? "正在保存…" : "保存新的PIN"}</Text></Pressable></View></View></ScreenContainer>;
}

const styles = StyleSheet.create({ page: { flex: 1, padding: 20, backgroundColor: "#FFF9F0" }, back: { width: 38, height: 38, borderRadius: 19, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EEE7DE" }, backText: { color: "#6E665E", fontSize: 31, marginTop: -4 }, title: { color: "#2E2A25", fontSize: 24, fontWeight: "900", marginTop: 28 }, subtitle: { color: "#776E66", fontSize: 13, lineHeight: 20, marginTop: 8 }, card: { backgroundColor: "#FFFFFF", borderRadius: 22, padding: 19, marginTop: 22, borderWidth: 1, borderColor: "#EEE7DE" }, label: { color: "#504940", fontSize: 13, fontWeight: "900", marginTop: 4 }, input: { height: 48, borderRadius: 13, borderWidth: 1, borderColor: "#E7DED4", marginTop: 8, marginBottom: 16, paddingHorizontal: 15, color: "#2E2A25", fontSize: 21, letterSpacing: 8, textAlign: "center" }, save: { backgroundColor: "#5D58B5", borderRadius: 14, alignItems: "center", paddingVertical: 14, marginTop: 4 }, saveText: { color: "#FFFFFF", fontSize: 14, fontWeight: "900" } });
