import { useCallback, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect, useRouter } from "expo-router";

import { ChildProfile, createChildProfile, loadFamilyState, setActiveProfile } from "@/lib/learning-progress";
import { ScreenContainer } from "@/components/screen-container";
import { isParentSessionUnlocked } from "@/lib/parent-security";

const AVATARS = ["🐇", "🐼", "🦊", "🐯"];

export default function ChildrenScreen() {
  const router = useRouter();
  const [profiles, setProfiles] = useState<ChildProfile[]>([]);
  const [activeId, setActiveId] = useState("");
  const [name, setName] = useState("");
  const [avatar, setAvatar] = useState(AVATARS[0]);
  const refresh = useCallback(() => { loadFamilyState().then((family) => { setProfiles(family.profiles); setActiveId(family.activeProfileId); }); }, []);
  useFocusEffect(useCallback(() => { isParentSessionUnlocked().then((unlocked) => { if (!unlocked) router.replace({ pathname: "/parent-gate", params: { target: "children" } } as never); else refresh(); }); }, [refresh, router]));
  const select = async (id: string) => { await setActiveProfile(id); refresh(); router.back(); };
  const add = async () => { await createChildProfile(name, avatar); setName(""); refresh(); router.back(); };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><FlatList data={profiles} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.top}><Pressable accessibilityRole="button" accessibilityLabel="返回我的学习" onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><Text style={styles.nav}>儿童档案</Text><View style={styles.space} /></View><Text style={styles.title}>选择正在学习的小朋友</Text><Text style={styles.subtitle}>每位孩子都有独立的关卡、星星、复习词和学习报告。</Text></>} renderItem={({ item }) => <Pressable accessibilityRole="button" accessibilityLabel={`切换到${item.name}的学习档案`} onPress={() => select(item.id)} style={[styles.profileCard, item.id === activeId && styles.activeCard]}><Text style={styles.avatar}>{item.avatar}</Text><View style={styles.profileCopy}><Text style={styles.profileName}>{item.name}</Text><Text style={styles.profileMeta}>已完成 {item.progress.completedLessonIds.length} 关 · {item.progress.totalStars} 颗星</Text></View><Text style={styles.check}>{item.id === activeId ? "✓" : ""}</Text></Pressable>} ListFooterComponent={<View style={styles.addBox}><Text style={styles.addTitle}>添加一位学习者</Text><TextInput value={name} onChangeText={setName} placeholder="输入孩子昵称" placeholderTextColor="#9B9289" style={styles.input} maxLength={16} returnKeyType="done" /><View style={styles.avatars}>{AVATARS.map((item) => <Pressable accessibilityRole="button" accessibilityLabel={`选择头像${item}`} key={item} onPress={() => setAvatar(item)} style={[styles.avatarChoice, avatar === item && styles.avatarSelected]}><Text style={styles.avatarText}>{item}</Text></Pressable>)}</View><Pressable accessibilityRole="button" accessibilityLabel="创建新的儿童档案" onPress={add} style={styles.addButton}><Text style={styles.addText}>创建儿童档案</Text></Pressable></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 40, gap: 12 }, top: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, back: { width: 38, height: 38, borderRadius: 19, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EEE7DE" }, backText: { color: "#6E665E", fontSize: 31, marginTop: -4 }, nav: { color: "#2E2A25", fontSize: 16, fontWeight: "900" }, space: { width: 38 }, title: { color: "#2E2A25", fontSize: 23, fontWeight: "900", marginTop: 24 }, subtitle: { color: "#786F67", fontSize: 13, lineHeight: 19, marginTop: 7, marginBottom: 11 }, profileCard: { minHeight: 86, backgroundColor: "#FFFFFF", borderRadius: 20, borderWidth: 1, borderColor: "#EEE7DE", padding: 15, flexDirection: "row", alignItems: "center" }, activeCard: { borderWidth: 2, borderColor: "#46A758", backgroundColor: "#F4FCF6" }, avatar: { fontSize: 32, marginRight: 13 }, profileCopy: { flex: 1 }, profileName: { color: "#2E2A25", fontSize: 16, fontWeight: "900" }, profileMeta: { color: "#7B726A", fontSize: 12, marginTop: 5 }, check: { color: "#2D8441", fontSize: 23, fontWeight: "900" }, addBox: { marginTop: 8, padding: 18, backgroundColor: "#FFF0D7", borderRadius: 22 }, addTitle: { color: "#80531E", fontSize: 16, fontWeight: "900" }, input: { height: 46, backgroundColor: "#FFFFFF", borderRadius: 13, paddingHorizontal: 13, color: "#2E2A25", marginTop: 13 }, avatars: { flexDirection: "row", gap: 10, marginTop: 13 }, avatarChoice: { width: 43, height: 43, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF" }, avatarSelected: { borderWidth: 2, borderColor: "#F5803E" }, avatarText: { fontSize: 22 }, addButton: { backgroundColor: "#F5803E", borderRadius: 13, alignItems: "center", paddingVertical: 12, marginTop: 15 }, addText: { color: "#FFFFFF", fontWeight: "900", fontSize: 14 } });
