import { useCallback, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import QRCode from "react-native-qrcode-svg";

import { createSyncCode, decryptFamilyBackup, encryptFamilyBackup, type EncryptedBackupEnvelope } from "@/lib/encrypted-backup";
import { isParentSessionUnlocked } from "@/lib/parent-security";
import { loadSyncExpiryReminder, scheduleSyncExpiryReminder } from "@/lib/sync-reminders";
import { logParentSecurityAction } from "@/lib/parent-security-log";
import { loadFamilyState, saveFamilyState } from "@/lib/learning-progress";
import { trpc } from "@/lib/trpc";
import { ScreenContainer } from "@/components/screen-container";

export default function CloudSyncScreen() {
  const router = useRouter();
  const { syncCode: scannedCode } = useLocalSearchParams<{ syncCode?: string }>();
  const utils = trpc.useUtils();
  const upload = trpc.sync.upload.useMutation();
  const [password, setPassword] = useState("");
  const [code, setCode] = useState("");
  const [createdCode, setCreatedCode] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [reminderText, setReminderText] = useState("");
  useFocusEffect(useCallback(() => { isParentSessionUnlocked().then((unlocked) => { if (!unlocked) router.replace({ pathname: "/parent-gate", params: { target: "parent-settings" } } as never); }); }, [router]));
  useFocusEffect(useCallback(() => { if (scannedCode) setCode(scannedCode.toUpperCase()); loadSyncExpiryReminder().then((reminder) => { if (reminder) setReminderText(`最近同步码将于 ${new Date(reminder.expiresAt).toLocaleDateString()} 到期。`); }); }, [scannedCode]));
  const makeSync = async () => { setBusy(true); try { const syncCode = await createSyncCode(); const envelope = await encryptFamilyBackup(await loadFamilyState(), password); await upload.mutateAsync({ syncCode, encryptedPayload: JSON.stringify(envelope) }); const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000); await scheduleSyncExpiryReminder(syncCode, expiresAt); await logParentSecurityAction("sync_created"); setReminderText(`已尝试设置到期前提醒；同步码将于 ${expiresAt.toLocaleDateString()} 到期。`); setCreatedCode(syncCode); } catch (error) { Alert.alert("未能创建同步码", error instanceof Error ? error.message : "请稍后再试。"); } finally { setBusy(false); } };
  const restore = async () => { setBusy(true); try { const syncCode = code.trim().toUpperCase(); const remote = await utils.sync.get.fetch({ syncCode }); if (!remote) throw new Error("未找到该同步码对应的加密备份。"); const backup = decryptFamilyBackup(JSON.parse(remote.encryptedPayload) as EncryptedBackupEnvelope, password); Alert.alert("确认恢复同步档案", `将用同步码中的 ${backup.family.profiles.length} 个儿童档案覆盖当前设备数据。`, [{ text: "取消", style: "cancel" }, { text: "确认恢复", style: "destructive", onPress: async () => { await saveFamilyState(backup.family); await logParentSecurityAction("sync_restored"); Alert.alert("恢复完成", "已恢复加密同步档案。" ); } }]); } catch (error) { Alert.alert("未能恢复", error instanceof Error ? error.message : "请检查同步码和备份密码。"); } finally { setBusy(false); } };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.page}><View style={styles.top}><Pressable accessibilityRole="button" accessibilityLabel="返回家长设置" onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><Text style={styles.nav}>加密同步码</Text><View style={styles.space} /></View><Text style={styles.title}>家长主动同步，不需要账号</Text><Text style={styles.subtitle}>儿童档案默认只保存在本机。只有你主动创建同步码时，才会上传一份由备份密码加密的密文；服务器无法读取档案内容。</Text>{reminderText ? <Text style={styles.reminder}>{reminderText}</Text> : null}<View style={styles.card}><Text style={styles.cardTitle}>1. 创建加密同步码</Text><TextInput value={password} onChangeText={setPassword} placeholder="设置至少8位备份密码" placeholderTextColor="#9B9289" secureTextEntry style={styles.input} /><Pressable accessibilityRole="button" accessibilityLabel="创建加密同步码" onPress={makeSync} disabled={busy} style={[styles.primary, busy && { opacity: 0.6 }]}><Text style={styles.primaryText}>{busy ? "处理中…" : "创建同步码"}</Text></Pressable>{createdCode ? <View style={styles.codeBox}><Text style={styles.codeHint}>请在另一台设备输入以下同步码，并使用同一备份密码。同步码7天有效：</Text><Text selectable style={styles.code}>{createdCode}</Text><View style={styles.qr}><QRCode value={createdCode} size={142} color="#2E2A25" backgroundColor="#FFFFFF" /></View><Text style={styles.qrHint}>也可以让另一台设备扫描此二维码</Text></View> : null}</View><View style={styles.card}><Text style={styles.cardTitle}>2. 在另一台设备恢复</Text><TextInput value={code} onChangeText={(value) => setCode(value.toUpperCase())} placeholder="例如 ABCDE-F0123-45678" placeholderTextColor="#9B9289" autoCapitalize="characters" style={styles.input} /><Pressable accessibilityRole="button" accessibilityLabel="扫描同步码二维码" onPress={() => router.push("/scan-sync" as never)} style={styles.scan}><Text style={styles.scanText}>扫描二维码填入</Text></Pressable><TextInput value={password} onChangeText={setPassword} placeholder="输入备份密码" placeholderTextColor="#9B9289" secureTextEntry style={styles.input} /><Pressable accessibilityRole="button" accessibilityLabel="使用同步码恢复档案" onPress={restore} disabled={busy} style={[styles.secondary, busy && { opacity: 0.6 }]}><Text style={styles.secondaryText}>恢复加密档案</Text></Pressable></View><View style={styles.note}><Text style={styles.noteTitle}>隐私说明</Text><Text style={styles.noteText}>不会创建账号、不会自动同步、不会提供密码找回。同步码仅保留7天；请自行妥善保存同步码和备份密码，两者缺失时无法恢复档案。</Text></View></View></ScreenContainer>;
}

const styles = StyleSheet.create({ page: { flex: 1, padding: 20, backgroundColor: "#FFF9F0" }, top: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, back: { width: 38, height: 38, borderRadius: 19, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EEE7DE" }, backText: { color: "#6E665E", fontSize: 31, marginTop: -4 }, nav: { color: "#2E2A25", fontSize: 16, fontWeight: "900" }, space: { width: 38 }, title: { color: "#2E2A25", fontSize: 23, lineHeight: 31, fontWeight: "900", marginTop: 24 }, subtitle: { color: "#786F67", fontSize: 13, lineHeight: 20, marginTop: 8 }, reminder: { color: "#5D58B5", backgroundColor: "#F1EEFF", borderRadius: 12, padding: 10, fontSize: 12, lineHeight: 18, marginTop: 12 }, card: { backgroundColor: "#FFFFFF", borderRadius: 21, padding: 17, marginTop: 16, borderWidth: 1, borderColor: "#EEE7DE" }, cardTitle: { color: "#2E2A25", fontSize: 16, fontWeight: "900" }, input: { height: 47, backgroundColor: "#FFFDF9", borderRadius: 13, borderWidth: 1, borderColor: "#E7DED4", color: "#2E2A25", paddingHorizontal: 13, marginTop: 12 }, primary: { backgroundColor: "#5D58B5", borderRadius: 13, alignItems: "center", paddingVertical: 12, marginTop: 12 }, primaryText: { color: "#FFFFFF", fontWeight: "900", fontSize: 14 }, secondary: { backgroundColor: "#F5F2FF", borderRadius: 13, alignItems: "center", paddingVertical: 12, marginTop: 8 }, secondaryText: { color: "#5D58B5", fontWeight: "900", fontSize: 14 }, scan: { backgroundColor: "#E7F6EB", borderRadius: 11, alignItems: "center", paddingVertical: 10, marginTop: 8 }, scanText: { color: "#33743F", fontSize: 13, fontWeight: "900" }, codeBox: { backgroundColor: "#E7F6EB", borderRadius: 14, padding: 13, marginTop: 13, alignItems: "center" }, codeHint: { color: "#51755A", fontSize: 12, lineHeight: 18, alignSelf: "stretch" }, code: { color: "#28743D", fontSize: 18, letterSpacing: 1.5, fontWeight: "900", marginTop: 8 }, qr: { backgroundColor: "#FFFFFF", borderRadius: 12, padding: 10, marginTop: 12 }, qrHint: { color: "#51755A", fontSize: 11, marginTop: 8 }, note: { backgroundColor: "#FFF0D7", borderRadius: 19, padding: 16, marginTop: 14 }, noteTitle: { color: "#89541E", fontSize: 14, fontWeight: "900" }, noteText: { color: "#806241", fontSize: 12, lineHeight: 19, marginTop: 6 } });
