import { useCallback, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { useFocusEffect, useRouter } from "expo-router";

import { loadProgress } from "@/lib/learning-progress";
import { DEFAULT_REMINDER_SETTINGS, disableReviewReminder, loadReminderSettings, scheduleNextReviewReminder, type ReminderSettings } from "@/lib/review-reminders";
import { ScreenContainer } from "@/components/screen-container";

const TIMES = [{ label: "17:30", hour: 17, minute: 30 }, { label: "19:00", hour: 19, minute: 0 }, { label: "20:00", hour: 20, minute: 0 }];

export default function ReminderSettingsScreen() {
  const router = useRouter();
  const [settings, setSettings] = useState<ReminderSettings>(DEFAULT_REMINDER_SETTINGS);
  useFocusEffect(useCallback(() => { loadReminderSettings().then(setSettings); }, []));
  const enable = async (next: ReminderSettings) => { try { const progress = await loadProgress(); const saved = await scheduleNextReviewReminder(progress, { ...next, enabled: true }); setSettings(saved); Alert.alert("提醒已开启", `下次有到期错题时，将在 ${String(saved.hour).padStart(2, "0")}:${String(saved.minute).padStart(2, "0")} 提醒复习。`); } catch { Alert.alert("未能开启提醒", "请在系统设置中允许通知权限后重试。"); } };
  const disable = async () => { const saved = await disableReviewReminder(); setSettings(saved); };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.page}><View style={styles.top}><Pressable accessibilityRole="button" accessibilityLabel="返回复习页" onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><Text style={styles.nav}>复习提醒</Text><View style={styles.space} /></View><Text style={styles.title}>让错题在合适的时间回来</Text><Text style={styles.subtitle}>答错的词会在第1、3、7、14天再次进入复习队列。提醒只在有到期词汇时安排。</Text><View style={styles.card}><Text style={styles.cardTitle}>每日提醒时间</Text><View style={styles.times}>{TIMES.map((time) => <Pressable key={time.label} accessibilityRole="button" accessibilityLabel={`设置提醒时间为${time.label}`} onPress={() => enable({ ...settings, hour: time.hour, minute: time.minute })} style={[styles.timeButton, settings.hour === time.hour && settings.minute === time.minute && styles.selected]}><Text style={[styles.timeText, settings.hour === time.hour && settings.minute === time.minute && styles.selectedText]}>{time.label}</Text></Pressable>)}</View><Pressable accessibilityRole="switch" accessibilityState={{ checked: settings.enabled }} onPress={() => settings.enabled ? disable() : enable(settings)} style={[styles.switchButton, settings.enabled && styles.switchOn]}><Text style={styles.switchText}>{settings.enabled ? "提醒已开启" : "开启复习提醒"}</Text></Pressable></View><View style={styles.note}><Text style={styles.noteTitle}>提示</Text><Text style={styles.noteText}>首次开启时，应用会请求系统通知权限。关闭提醒不会删除你的错题与复习计划。</Text></View></View></ScreenContainer>;
}

const styles = StyleSheet.create({ page: { flex: 1, padding: 20, backgroundColor: "#FFF9F0" }, top: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, back: { width: 38, height: 38, borderRadius: 19, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EEE7DE" }, backText: { color: "#6E665E", fontSize: 31, marginTop: -4 }, nav: { color: "#2E2A25", fontSize: 16, fontWeight: "900" }, space: { width: 38 }, title: { color: "#2E2A25", fontSize: 24, lineHeight: 31, fontWeight: "900", marginTop: 26 }, subtitle: { color: "#786F67", fontSize: 14, lineHeight: 21, marginTop: 9 }, card: { backgroundColor: "#FFFFFF", borderRadius: 23, padding: 18, marginTop: 23, borderWidth: 1, borderColor: "#EEE7DE" }, cardTitle: { color: "#2E2A25", fontSize: 16, fontWeight: "900" }, times: { flexDirection: "row", gap: 8, marginTop: 15 }, timeButton: { flex: 1, borderRadius: 12, borderWidth: 1, borderColor: "#E9E2D9", paddingVertical: 11, alignItems: "center" }, selected: { backgroundColor: "#FFF0D7", borderColor: "#F5803E" }, timeText: { color: "#756D65", fontSize: 13, fontWeight: "800" }, selectedText: { color: "#A65B1B" }, switchButton: { marginTop: 17, borderRadius: 14, paddingVertical: 13, alignItems: "center", backgroundColor: "#E6E0D9" }, switchOn: { backgroundColor: "#46A758" }, switchText: { color: "#FFFFFF", fontSize: 14, fontWeight: "900" }, note: { marginTop: 14, backgroundColor: "#F5F2FF", borderRadius: 19, padding: 16 }, noteTitle: { color: "#5D58B5", fontSize: 14, fontWeight: "900" }, noteText: { color: "#726DA6", fontSize: 12, lineHeight: 18, marginTop: 6 } });
