import { useCallback, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { useFocusEffect, useRouter } from "expo-router";

import { clearParentSecurityLogs, loadParentSecurityLogs, type ParentSecurityAction, type ParentSecurityLog } from "@/lib/parent-security-log";
import { isParentSessionUnlocked } from "@/lib/parent-security";
import { ScreenContainer } from "@/components/screen-container";

const labels: Record<ParentSecurityAction, string> = { parent_locked: "已紧急锁定家长模式", pin_changed: "已修改家长PIN", biometric_enabled: "已开启生物识别", biometric_disabled: "已关闭生物识别", backup_exported: "已导出本地备份", backup_restored: "已恢复本地备份", sync_created: "已创建加密同步码", sync_restored: "已恢复加密同步档案", recent_learning_cleared: "已清除最近学习入口" };
export default function SecurityLogScreen() {
  const router = useRouter(); const [logs, setLogs] = useState<ParentSecurityLog[]>([]);
  const refresh = useCallback(() => { loadParentSecurityLogs().then(setLogs); }, []);
  useFocusEffect(useCallback(() => { isParentSessionUnlocked().then((unlocked) => { if (!unlocked) router.replace({ pathname: "/parent-gate", params: { target: "parent-settings" } } as never); else refresh(); }); }, [refresh, router]));
  const clear = () => Alert.alert("清空安全日志", "此操作只会删除本机的家长安全操作记录。", [{ text: "取消", style: "cancel" }, { text: "清空", style: "destructive", onPress: async () => { await clearParentSecurityLogs(); setLogs([]); } }]);
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><FlatList data={logs} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.top}><Pressable accessibilityRole="button" accessibilityLabel="返回家长设置" onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><Text style={styles.nav}>安全操作日志</Text><Pressable accessibilityRole="button" accessibilityLabel="清空安全操作日志" onPress={clear} style={styles.clear}><Text style={styles.clearText}>清空</Text></Pressable></View><Text style={styles.title}>本机家长安全记录</Text><Text style={styles.subtitle}>仅记录此设备上的家长保护、备份和同步操作；不记录PIN、备份密码或儿童学习内容。</Text></>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>暂无安全操作记录</Text><Text style={styles.emptyText}>修改PIN、创建同步码或紧急锁定后会显示在这里。</Text></View>} renderItem={({ item }) => <View style={styles.item}><View style={styles.dot} /><View style={styles.itemText}><Text style={styles.itemTitle}>{labels[item.action]}</Text><Text style={styles.itemDate}>{new Date(item.createdAt).toLocaleString()}</Text></View></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 42, gap: 10 }, top: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, back: { width: 38, height: 38, borderRadius: 19, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EEE7DE" }, backText: { color: "#6E665E", fontSize: 31, marginTop: -4 }, nav: { color: "#2E2A25", fontSize: 16, fontWeight: "900" }, clear: { padding: 7 }, clearText: { color: "#B34E46", fontSize: 13, fontWeight: "900" }, title: { color: "#2E2A25", fontSize: 23, fontWeight: "900", marginTop: 24 }, subtitle: { color: "#786F67", fontSize: 13, lineHeight: 20, marginTop: 8 }, item: { backgroundColor: "#FFFFFF", borderRadius: 18, padding: 16, flexDirection: "row", alignItems: "center", borderWidth: 1, borderColor: "#EEE7DE" }, dot: { width: 9, height: 9, borderRadius: 5, backgroundColor: "#5D58B5", marginRight: 12 }, itemText: { flex: 1 }, itemTitle: { color: "#38312C", fontSize: 14, fontWeight: "900" }, itemDate: { color: "#8B8178", fontSize: 12, marginTop: 5 }, empty: { borderRadius: 20, backgroundColor: "#F5F2FF", padding: 22, alignItems: "center", marginTop: 16 }, emptyTitle: { color: "#5D58B5", fontSize: 15, fontWeight: "900" }, emptyText: { color: "#7D7690", fontSize: 12, lineHeight: 19, textAlign: "center", marginTop: 8 } });
