import { useCallback, useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { useFocusEffect, useRouter } from "expo-router";

import { RabbitAvatar } from "@/components/rabbit-avatar";
import { REVIEW_WORDS, type ReviewWord } from "@/lib/learning-data";
import { getDueReviewWordIds, recordReviewSuccess } from "@/lib/learning-progress";
import { scheduleNextReviewReminder } from "@/lib/review-reminders";
import { WordAudioButton } from "@/components/word-audio-button";
import { ScreenContainer } from "@/components/screen-container";
import { LoadingState } from "@/components/loading-state";
import { TransitionIn } from "@/components/transition-in";

export default function ReviewScreen() {
  const [reviewIds, setReviewIds] = useState<string[]>([]);
  const [revealed, setRevealed] = useState<string | null>(null);
  const [showAll, setShowAll] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const router = useRouter();
  useFocusEffect(useCallback(() => { let active = true; setIsLoading(true); void getDueReviewWordIds().then((ids) => { if (active) setReviewIds(ids); }).finally(() => { if (active) setIsLoading(false); }); return () => { active = false; }; }, []));
  const words = useMemo(() => reviewIds.length ? REVIEW_WORDS.filter((word) => reviewIds.includes(word.id)) : showAll ? REVIEW_WORDS : REVIEW_WORDS.slice(0, 6), [reviewIds, showAll]);
  const isPracticeMode = reviewIds.length > 0;
  const markKnown = async (word: ReviewWord) => { if (reviewIds.includes(word.id)) { const progress = await recordReviewSuccess(word.id); await scheduleNextReviewReminder(progress); setReviewIds((ids) => ids.filter((id) => id !== word.id)); } setRevealed(null); };

  return <ScreenContainer><FlatList data={isLoading ? [] : words} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.header}><View><Text style={styles.eyebrow}>{isPracticeMode ? "今日待复习" : showAll ? "完整词表" : "今日温习"}</Text><Text style={styles.title}>{isPracticeMode ? "按节奏复习，记得更牢" : "听一听，读一读，再记住它"}</Text><Text style={styles.subtitle}>错词将在第1、3、7、14天再次出现；示范按钮会获取IPA与在线示范音频。</Text></View><RabbitAvatar size={66} accent="#E7F7EB" /></View><View style={styles.headerActions}>{!isPracticeMode ? <Pressable accessibilityRole="button" accessibilityLabel={showAll ? "返回今日词汇" : "浏览完整词表"} onPress={() => setShowAll((value) => !value)} style={styles.browseButton}><Text style={styles.browseText}>{showAll ? "返回今日词汇" : `浏览完整词表 · ${REVIEW_WORDS.length} 词`}</Text></Pressable> : null}<Pressable accessibilityRole="button" accessibilityLabel="开始词义配图连线小游戏" onPress={() => router.push("/word-match" as never)} style={styles.matchButton}><Text style={styles.matchText}>🧩 词图连线</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="管理离线音频包" onPress={() => router.push("/audio-pack" as never)} style={styles.reminderButton}><Text style={styles.reminderText}>⬇ 音频包</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="设置复习提醒" onPress={() => router.push("/reminders" as never)} style={styles.reminderButton}><Text style={styles.reminderText}>⏰ 提醒</Text></Pressable></View></>} ListEmptyComponent={isLoading ? <LoadingState compact title="正在整理今天的复习词…" description="兔兔在查看需要巩固的内容" /> : null} renderItem={({ item }) => {
    const showMeaning = revealed === item.id;
    return <TransitionIn trigger={`${item.id}-${isPracticeMode ? "due" : "word"}`}><Pressable onPress={() => setRevealed(showMeaning ? null : item.id)} style={({ pressed }) => [styles.card, pressed && { opacity: 0.9 }]}><View style={styles.cardTop}><Text style={styles.level}>{item.levelId}</Text><WordAudioButton word={item.word} initialPhonetic={item.phonetic} /></View><Text style={styles.word}>{item.word}</Text>{showMeaning ? <View style={styles.answer}><Text style={styles.meaning}>{item.meaning}</Text><Text style={styles.example}>{item.example}</Text><View style={styles.actions}><Pressable accessibilityRole="button" accessibilityLabel={`进入 ${item.word} 的朗读评分`} onPress={() => router.push({ pathname: "/practice/[word]", params: { word: item.id } })} style={styles.readButton}><Text style={styles.readText}>🎙 评分练习</Text></Pressable></View>{isPracticeMode ? <Pressable accessibilityRole="button" accessibilityLabel={`完成 ${item.word} 的本轮复习`} onPress={() => markKnown(item)} style={styles.knownButton}><Text style={styles.knownText}>本轮记住了</Text></Pressable> : null}</View> : <Text style={styles.hint}>点击卡片翻开中文释义、音标和朗读练习</Text>}</Pressable></TransitionIn>;
  }} /></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { padding: 20, paddingBottom: 110, gap: 14 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }, eyebrow: { color: "#7B6FEA", fontSize: 13, fontWeight: "900" }, title: { color: "#2E2A25", fontSize: 23, lineHeight: 30, fontWeight: "900", marginTop: 5, maxWidth: 260 }, subtitle: { color: "#766E68", fontSize: 13, lineHeight: 19, marginTop: 6, maxWidth: 255 }, headerActions: { flexDirection: "row", gap: 8, marginBottom: 2, flexWrap: "wrap" }, browseButton: { alignSelf: "flex-start", backgroundColor: "#ECEBFF", borderRadius: 12, paddingVertical: 9, paddingHorizontal: 12 }, browseText: { color: "#5C58B5", fontWeight: "900", fontSize: 12 }, matchButton: { backgroundColor: "#E7F6EB", borderRadius: 12, paddingVertical: 9, paddingHorizontal: 11 }, matchText: { color: "#277B3B", fontWeight: "900", fontSize: 12 }, reminderButton: { backgroundColor: "#FFF0D7", borderRadius: 12, paddingVertical: 9, paddingHorizontal: 11 }, reminderText: { color: "#A65B1B", fontWeight: "900", fontSize: 12 }, card: { backgroundColor: "#FFFFFF", borderRadius: 24, padding: 20, borderWidth: 1, borderColor: "#EDE7DE", minHeight: 175 }, cardTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, level: { color: "#5B67CE", backgroundColor: "#EAEAFF", paddingVertical: 4, paddingHorizontal: 9, borderRadius: 9, fontWeight: "900", fontSize: 12 }, word: { fontSize: 29, color: "#2E2A25", fontWeight: "900", marginTop: 18 }, hint: { color: "#B0853C", fontSize: 13, marginTop: 21, fontWeight: "700" }, answer: { marginTop: 16 }, meaning: { color: "#2E2A25", fontSize: 20, fontWeight: "900" }, example: { color: "#736D65", fontSize: 14, lineHeight: 21, marginTop: 7 }, actions: { flexDirection: "row", gap: 9, marginTop: 13 }, readButton: { flex: 1, borderRadius: 12, backgroundColor: "#F5F2FF", paddingVertical: 10, alignItems: "center" }, readText: { color: "#5D57AF", fontSize: 12, fontWeight: "900" }, knownButton: { backgroundColor: "#46A758", borderRadius: 15, alignItems: "center", paddingVertical: 11, marginTop: 13 }, knownText: { color: "#FFFFFF", fontWeight: "900", fontSize: 14 },
});
